// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages_@home_zjupanda_odometer.proto

#ifndef PROTOBUF_messages_5f_40home_5fzjupanda_5fodometer_2eproto__INCLUDED
#define PROTOBUF_messages_5f_40home_5fzjupanda_5fodometer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_messages_5f_40home_5fzjupanda_5fodometer_2eproto();
void protobuf_AssignDesc_messages_5f_40home_5fzjupanda_5fodometer_2eproto();
void protobuf_ShutdownFile_messages_5f_40home_5fzjupanda_5fodometer_2eproto();

class Home_WheelsOmni;
class Home_VelocityOmni;
class Home_Odometer;

// ===================================================================

class Home_WheelsOmni : public ::google::protobuf::Message {
 public:
  Home_WheelsOmni();
  virtual ~Home_WheelsOmni();
  
  Home_WheelsOmni(const Home_WheelsOmni& from);
  
  inline Home_WheelsOmni& operator=(const Home_WheelsOmni& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Home_WheelsOmni& default_instance();
  
  void Swap(Home_WheelsOmni* other);
  
  // implements Message ----------------------------------------------
  
  Home_WheelsOmni* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Home_WheelsOmni& from);
  void MergeFrom(const Home_WheelsOmni& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required double w1 = 1;
  inline bool has_w1() const;
  inline void clear_w1();
  static const int kW1FieldNumber = 1;
  inline double w1() const;
  inline void set_w1(double value);
  
  // required double w2 = 2;
  inline bool has_w2() const;
  inline void clear_w2();
  static const int kW2FieldNumber = 2;
  inline double w2() const;
  inline void set_w2(double value);
  
  // required double w3 = 3;
  inline bool has_w3() const;
  inline void clear_w3();
  static const int kW3FieldNumber = 3;
  inline double w3() const;
  inline void set_w3(double value);
  
  // required double w4 = 4;
  inline bool has_w4() const;
  inline void clear_w4();
  static const int kW4FieldNumber = 4;
  inline double w4() const;
  inline void set_w4(double value);
  
  // @@protoc_insertion_point(class_scope:Home_WheelsOmni)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  double w1_;
  double w2_;
  double w3_;
  double w4_;
  friend void  protobuf_AddDesc_messages_5f_40home_5fzjupanda_5fodometer_2eproto();
  friend void protobuf_AssignDesc_messages_5f_40home_5fzjupanda_5fodometer_2eproto();
  friend void protobuf_ShutdownFile_messages_5f_40home_5fzjupanda_5fodometer_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Home_WheelsOmni* default_instance_;
};
// -------------------------------------------------------------------

class Home_VelocityOmni : public ::google::protobuf::Message {
 public:
  Home_VelocityOmni();
  virtual ~Home_VelocityOmni();
  
  Home_VelocityOmni(const Home_VelocityOmni& from);
  
  inline Home_VelocityOmni& operator=(const Home_VelocityOmni& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Home_VelocityOmni& default_instance();
  
  void Swap(Home_VelocityOmni* other);
  
  // implements Message ----------------------------------------------
  
  Home_VelocityOmni* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Home_VelocityOmni& from);
  void MergeFrom(const Home_VelocityOmni& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required double vx = 1;
  inline bool has_vx() const;
  inline void clear_vx();
  static const int kVxFieldNumber = 1;
  inline double vx() const;
  inline void set_vx(double value);
  
  // required double vy = 2;
  inline bool has_vy() const;
  inline void clear_vy();
  static const int kVyFieldNumber = 2;
  inline double vy() const;
  inline void set_vy(double value);
  
  // required double w = 3;
  inline bool has_w() const;
  inline void clear_w();
  static const int kWFieldNumber = 3;
  inline double w() const;
  inline void set_w(double value);
  
  // @@protoc_insertion_point(class_scope:Home_VelocityOmni)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  double vx_;
  double vy_;
  double w_;
  friend void  protobuf_AddDesc_messages_5f_40home_5fzjupanda_5fodometer_2eproto();
  friend void protobuf_AssignDesc_messages_5f_40home_5fzjupanda_5fodometer_2eproto();
  friend void protobuf_ShutdownFile_messages_5f_40home_5fzjupanda_5fodometer_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Home_VelocityOmni* default_instance_;
};
// -------------------------------------------------------------------

class Home_Odometer : public ::google::protobuf::Message {
 public:
  Home_Odometer();
  virtual ~Home_Odometer();
  
  Home_Odometer(const Home_Odometer& from);
  
  inline Home_Odometer& operator=(const Home_Odometer& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Home_Odometer& default_instance();
  
  void Swap(Home_Odometer* other);
  
  // implements Message ----------------------------------------------
  
  Home_Odometer* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Home_Odometer& from);
  void MergeFrom(const Home_Odometer& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 cycle = 1;
  inline bool has_cycle() const;
  inline void clear_cycle();
  static const int kCycleFieldNumber = 1;
  inline ::google::protobuf::uint32 cycle() const;
  inline void set_cycle(::google::protobuf::uint32 value);
  
  // required double x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline double x() const;
  inline void set_x(double value);
  
  // required double y = 3;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 3;
  inline double y() const;
  inline void set_y(double value);
  
  // required double angle = 4;
  inline bool has_angle() const;
  inline void clear_angle();
  static const int kAngleFieldNumber = 4;
  inline double angle() const;
  inline void set_angle(double value);
  
  // optional .Home_WheelsOmni wheels = 5;
  inline bool has_wheels() const;
  inline void clear_wheels();
  static const int kWheelsFieldNumber = 5;
  inline const ::Home_WheelsOmni& wheels() const;
  inline ::Home_WheelsOmni* mutable_wheels();
  
  // optional .Home_VelocityOmni lv = 6;
  inline bool has_lv() const;
  inline void clear_lv();
  static const int kLvFieldNumber = 6;
  inline const ::Home_VelocityOmni& lv() const;
  inline ::Home_VelocityOmni* mutable_lv();
  
  // optional .Home_VelocityOmni gv = 7;
  inline bool has_gv() const;
  inline void clear_gv();
  static const int kGvFieldNumber = 7;
  inline const ::Home_VelocityOmni& gv() const;
  inline ::Home_VelocityOmni* mutable_gv();
  
  // @@protoc_insertion_point(class_scope:Home_Odometer)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::uint32 cycle_;
  double x_;
  double y_;
  double angle_;
  ::Home_WheelsOmni* wheels_;
  ::Home_VelocityOmni* lv_;
  ::Home_VelocityOmni* gv_;
  friend void  protobuf_AddDesc_messages_5f_40home_5fzjupanda_5fodometer_2eproto();
  friend void protobuf_AssignDesc_messages_5f_40home_5fzjupanda_5fodometer_2eproto();
  friend void protobuf_ShutdownFile_messages_5f_40home_5fzjupanda_5fodometer_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Home_Odometer* default_instance_;
};
// ===================================================================


// ===================================================================

// Home_WheelsOmni

// required double w1 = 1;
inline bool Home_WheelsOmni::has_w1() const {
  return _has_bit(0);
}
inline void Home_WheelsOmni::clear_w1() {
  w1_ = 0;
  _clear_bit(0);
}
inline double Home_WheelsOmni::w1() const {
  return w1_;
}
inline void Home_WheelsOmni::set_w1(double value) {
  _set_bit(0);
  w1_ = value;
}

// required double w2 = 2;
inline bool Home_WheelsOmni::has_w2() const {
  return _has_bit(1);
}
inline void Home_WheelsOmni::clear_w2() {
  w2_ = 0;
  _clear_bit(1);
}
inline double Home_WheelsOmni::w2() const {
  return w2_;
}
inline void Home_WheelsOmni::set_w2(double value) {
  _set_bit(1);
  w2_ = value;
}

// required double w3 = 3;
inline bool Home_WheelsOmni::has_w3() const {
  return _has_bit(2);
}
inline void Home_WheelsOmni::clear_w3() {
  w3_ = 0;
  _clear_bit(2);
}
inline double Home_WheelsOmni::w3() const {
  return w3_;
}
inline void Home_WheelsOmni::set_w3(double value) {
  _set_bit(2);
  w3_ = value;
}

// required double w4 = 4;
inline bool Home_WheelsOmni::has_w4() const {
  return _has_bit(3);
}
inline void Home_WheelsOmni::clear_w4() {
  w4_ = 0;
  _clear_bit(3);
}
inline double Home_WheelsOmni::w4() const {
  return w4_;
}
inline void Home_WheelsOmni::set_w4(double value) {
  _set_bit(3);
  w4_ = value;
}

// -------------------------------------------------------------------

// Home_VelocityOmni

// required double vx = 1;
inline bool Home_VelocityOmni::has_vx() const {
  return _has_bit(0);
}
inline void Home_VelocityOmni::clear_vx() {
  vx_ = 0;
  _clear_bit(0);
}
inline double Home_VelocityOmni::vx() const {
  return vx_;
}
inline void Home_VelocityOmni::set_vx(double value) {
  _set_bit(0);
  vx_ = value;
}

// required double vy = 2;
inline bool Home_VelocityOmni::has_vy() const {
  return _has_bit(1);
}
inline void Home_VelocityOmni::clear_vy() {
  vy_ = 0;
  _clear_bit(1);
}
inline double Home_VelocityOmni::vy() const {
  return vy_;
}
inline void Home_VelocityOmni::set_vy(double value) {
  _set_bit(1);
  vy_ = value;
}

// required double w = 3;
inline bool Home_VelocityOmni::has_w() const {
  return _has_bit(2);
}
inline void Home_VelocityOmni::clear_w() {
  w_ = 0;
  _clear_bit(2);
}
inline double Home_VelocityOmni::w() const {
  return w_;
}
inline void Home_VelocityOmni::set_w(double value) {
  _set_bit(2);
  w_ = value;
}

// -------------------------------------------------------------------

// Home_Odometer

// required uint32 cycle = 1;
inline bool Home_Odometer::has_cycle() const {
  return _has_bit(0);
}
inline void Home_Odometer::clear_cycle() {
  cycle_ = 0u;
  _clear_bit(0);
}
inline ::google::protobuf::uint32 Home_Odometer::cycle() const {
  return cycle_;
}
inline void Home_Odometer::set_cycle(::google::protobuf::uint32 value) {
  _set_bit(0);
  cycle_ = value;
}

// required double x = 2;
inline bool Home_Odometer::has_x() const {
  return _has_bit(1);
}
inline void Home_Odometer::clear_x() {
  x_ = 0;
  _clear_bit(1);
}
inline double Home_Odometer::x() const {
  return x_;
}
inline void Home_Odometer::set_x(double value) {
  _set_bit(1);
  x_ = value;
}

// required double y = 3;
inline bool Home_Odometer::has_y() const {
  return _has_bit(2);
}
inline void Home_Odometer::clear_y() {
  y_ = 0;
  _clear_bit(2);
}
inline double Home_Odometer::y() const {
  return y_;
}
inline void Home_Odometer::set_y(double value) {
  _set_bit(2);
  y_ = value;
}

// required double angle = 4;
inline bool Home_Odometer::has_angle() const {
  return _has_bit(3);
}
inline void Home_Odometer::clear_angle() {
  angle_ = 0;
  _clear_bit(3);
}
inline double Home_Odometer::angle() const {
  return angle_;
}
inline void Home_Odometer::set_angle(double value) {
  _set_bit(3);
  angle_ = value;
}

// optional .Home_WheelsOmni wheels = 5;
inline bool Home_Odometer::has_wheels() const {
  return _has_bit(4);
}
inline void Home_Odometer::clear_wheels() {
  if (wheels_ != NULL) wheels_->::Home_WheelsOmni::Clear();
  _clear_bit(4);
}
inline const ::Home_WheelsOmni& Home_Odometer::wheels() const {
  return wheels_ != NULL ? *wheels_ : *default_instance_->wheels_;
}
inline ::Home_WheelsOmni* Home_Odometer::mutable_wheels() {
  _set_bit(4);
  if (wheels_ == NULL) wheels_ = new ::Home_WheelsOmni;
  return wheels_;
}

// optional .Home_VelocityOmni lv = 6;
inline bool Home_Odometer::has_lv() const {
  return _has_bit(5);
}
inline void Home_Odometer::clear_lv() {
  if (lv_ != NULL) lv_->::Home_VelocityOmni::Clear();
  _clear_bit(5);
}
inline const ::Home_VelocityOmni& Home_Odometer::lv() const {
  return lv_ != NULL ? *lv_ : *default_instance_->lv_;
}
inline ::Home_VelocityOmni* Home_Odometer::mutable_lv() {
  _set_bit(5);
  if (lv_ == NULL) lv_ = new ::Home_VelocityOmni;
  return lv_;
}

// optional .Home_VelocityOmni gv = 7;
inline bool Home_Odometer::has_gv() const {
  return _has_bit(6);
}
inline void Home_Odometer::clear_gv() {
  if (gv_ != NULL) gv_->::Home_VelocityOmni::Clear();
  _clear_bit(6);
}
inline const ::Home_VelocityOmni& Home_Odometer::gv() const {
  return gv_ != NULL ? *gv_ : *default_instance_->gv_;
}
inline ::Home_VelocityOmni* Home_Odometer::mutable_gv() {
  _set_bit(6);
  if (gv_ == NULL) gv_ = new ::Home_VelocityOmni;
  return gv_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messages_5f_40home_5fzjupanda_5fodometer_2eproto__INCLUDED
